spring:
  main:
    allow-bean-definition-overriding: true
  config:
    import:
      - optional:classpath:.db-property.env[.properties]
  datasource:
    hikari:
#      driver-class-name: org.mariadb.jdbc.Driver
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: ${DB_URL:jdbc:log4jdbc:mariadb://localhost:33318/testdb}
      username: ${DB_USER:limeEdu}
      password: ${DB_PASSWORD:limeEdu1!}
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.lime.persistence.domain
